### ISSUE TITLE
これメンテナンスします？

### ISSUE THREAD

**Issue by anoyetta** [eai04191/Actor#1]
ACTの導入は何かと難しく、正しくない環境で使い続けている人が多いです。
また、リテラシーのあまり高くない人は導入そのものにムリがあります。

このプロジェクトならば万人に勧められますし、私もプラグインに対する質問があったときに誘導できるので大変助かります。

Hojoring への対応、またその後のメンテナンスを継続してもらえるでしょうか？

**Comment by eai04191** [comment]
とりあえずHojoringに対応しました。
私がACTの入れ方を解説するのがめんどくさくて作ったものですし、更新などは出来る限り対応したいと思っています。

**Comment by anoyetta** [comment]
ありがとうございます。導入に苦戦してる人にはこちらを使うように促しますわー。
